[tool.poetry]
name = "aiarena-docker"
version = "0.1.0"
description = ""
authors = ["AI Arena <staff@aiarena.net>"]

[tool.poetry.dependencies]
python = ">=3.8 <3.11"
aiohttp = "^3.7.4"
aiohttp-jinja2 = "^1.5"
attrs = "^21.4.0"
burnysc2 = "^6.0.0"
certifi = "^2022.5.18"
future = "^0.18.2"
gym = "^0.23.1"
h5py = "^3.6.0"
imutils = "^0.5.4"
jinja2 = "^3.1.2"
keras = "^2.9.0"
loguru = "^0.6.0"
more-itertools = "^8.13.0"
multidict = "^6.0.2"
numpy = "^1.22.3"
opencv-contrib-python = "^4.5.5"
opencv-python = "^4.5.5"
pandas = "^1.4.2"
pipenv = "^2022.5.2"
portpicker = "^1.5.0"
protobuf = "^4.22.0"
psutil = "^5.9.0"
pyglet = "^1.5.26"
pysc2 = "^3.0.0"
pyyaml = "^6.0"
python-utils = "^3.2.3"
requests = "^2.27.1"
s2clientprotocol = "^5.0.9"
scikit-image = "^0.19.2"
scikit-learn = "^1.1.1"
scipy = "^1.8.1"
six = "^1.16.0"
sqlalchemy = "^1.4.36"
stable-baselines3 = "*"
tensorflow = "^2.9.0"
termcolor = "^1.1.0"
theano = "^1.0.5"
torch = "1.11.0"
torch-optimizer = "^0.3.0"
torchvision = "^0.12.0"
tqdm = "^4.64.0"
urllib3 = "^1.26.9"
uvloop = "^0.16.0"
virtualenv = "^20.14.1"
virtualenv-clone = "^0.5.7"
websockets = "^10.3"
yarl = "^1.7.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
